In [1]:
import numpy as np

In [3]:
data = np.array([[1,2],[3,4],[5,6]])
type(data)

numpy.ndarray

In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
data.ndim

2

In [6]:
data.shape

(3, 2)

In [7]:
data.size

6

In [8]:
x = np.array([-1,0,1])
y = np.array([-2,0,2])
X, Y = np.meshgrid(x, y)

In [9]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [10]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [13]:
np.empty(3, dtype=np.float)

array([1.07474606e-311, 0.00000000e+000, 1.46417710e-312])