In [1]:
import numpy as np

In [2]:
data = np.array([[1,2],[3,4],[5,6]])
type(data)

numpy.ndarray

In [3]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
data.ndim

2

In [5]:
data.shape

(3, 2)

In [6]:
data.size

6

In [7]:
x = np.array([-1,0,1])
y = np.array([-2,0,2])
X, Y = np.meshgrid(x, y)

In [8]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [9]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [10]:
np.empty(3, dtype=np.float)

array([1.35453266e-311, 0.00000000e+000, 1.01855863e-312])

In [16]:
a = np.array([1,2,3,4])

In [17]:
a.ndim

1

In [19]:
a.shape

(4,)

In [20]:
x1 = 5.4*np.ones(10)

In [21]:
x2 = np.full(10, 5.4)

In [22]:
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [23]:
x2

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [24]:
x1 = np.empty(5)

In [26]:
x1.fill(3.0)

In [27]:
x1

array([3., 3., 3., 3., 3.])

In [28]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [29]:
np.logspace(0,2,5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [30]:
np.empty(3)

array([1.35453266e-311, 0.00000000e+000, 1.01855863e-312])

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [32]:
def f(x):
    y = np.ones_like(x)
    return y

In [37]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [55]:
f = lambda m, n: n+10*m
A = np.fromfunction(f, (6,6),dtype = int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [56]:
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [57]:
A[1::2, 1::3]

array([[11, 14],
       [31, 34],
       [51, 54]])

In [58]:
B = A[1:5, 1:5]
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [59]:
B[:,:]=0

In [60]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [61]:
C = B[1:3, 1:3].copy()

In [62]:
C

array([[0, 0],
       [0, 0]])

In [63]:
C[:,:]=1

In [64]:
C

array([[1, 1],
       [1, 1]])

In [65]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [66]:
A = np.linspace(0,1,11)

In [67]:
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [68]:
A[[0,2,4]]

array([0. , 0.2, 0.4])

In [69]:
A = np.arange(10)

In [70]:
indices = [2,4,6]

In [71]:
B = A[indices]

In [72]:
B[0] = -1

In [73]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
A[indices] = -1

In [75]:
A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

In [81]:
data = np.array([[1,2],[3,4]])

In [82]:
data

array([[1, 2],
       [3, 4]])

In [85]:
data.ravel()

array([1, 2, 3, 4])

In [86]:
data.ravel().shape

(4,)

In [87]:
data = np.arange(0,5)

In [88]:
data

array([0, 1, 2, 3, 4])

In [89]:
column = data[:, np.newaxis]

In [90]:
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [91]:
row = data[np.newaxis, :]

In [92]:
row

array([[0, 1, 2, 3, 4]])

In [94]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [95]:
np.vstack((data,data,data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [96]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [97]:
data = data[:, np.newaxis]

In [98]:
data

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [99]:
x = np.array([1,2,3,4]).reshape(2,2)

In [100]:
x

array([[1, 2],
       [3, 4]])

In [101]:
z = np.array([[2,4]])

In [102]:
z

array([[2, 4]])

In [103]:
x/z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [104]:
zz = np.concatenate([z,z],axis=0)

In [105]:
zz

array([[2, 4],
       [2, 4]])

In [106]:
x/zz

array([[0.5, 0.5],
       [1.5, 1. ]])

In [112]:
z = np.array([[2],[4]])
z

array([[2],
       [4]])

In [113]:
x/z

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [115]:
x = np.linspace(-1,1,11)
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [116]:
y = np.sin(np.pi*x)
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [117]:
np.add(np.sin(x)**2, np.cos(x)**2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [118]:
def heaviside(x):
    return 1 if x >0 else 0
heaviside(-1)

0

In [119]:
heaviside(2)

1

In [120]:
heaviside = np.vectorize(heaviside)

In [121]:
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [122]:
## Nonetheless, np.vectorize can often be a quick and convenient way to vectorize a function written for scalar input.

In [123]:
data = np.random.normal(size=(15,15))
np.mean(data)

-0.011632272444189533

In [124]:
data.mean()

-0.011632272444189533

In [125]:
data = np.random.normal(size=(5,10,15))

In [126]:
data

array([[[ 1.70642756,  1.0149397 , -0.00960989,  0.29710372,
          0.52627252, -0.77114994, -1.24443544,  2.13601747,
          0.35013312,  0.38062867,  0.29908304, -0.22540463,
         -0.38623389,  0.17375786, -1.29383451],
        [-1.06613524,  1.70410939, -1.21319833, -1.28941797,
          0.62699967,  0.18661138, -0.87170493,  0.71094595,
          0.52714294,  1.36429112,  0.89140221,  0.01616189,
         -1.54747865,  0.83771145,  0.2401886 ],
        [ 0.16659037, -0.12874055, -0.53560357,  0.8874169 ,
          1.06634417, -0.05638132,  2.68382967,  0.91615902,
          0.5187992 , -1.06599466, -0.3377632 , -1.44895938,
          0.75058174,  0.08159418, -1.92629901],
        [-1.6571661 , -0.12074635, -1.58099914, -0.31495392,
         -0.65123521,  1.21991684,  1.27013949, -1.79185772,
         -0.9558605 , -0.32888987,  1.23807646, -0.74282065,
         -1.29758032,  1.15383781,  1.70757029],
        [-0.96142583, -2.30218498, -0.19088624, -0.01016066,
         -0

In [127]:
data.sum(axis=0).shape

(10, 15)

In [128]:
data.sum(axis=0)

array([[ 2.0756408 ,  0.44498241, -1.51914911,  0.67454032,  0.24536244,
        -1.34172173,  1.85357254,  4.53836061, -1.68425659,  2.24130857,
        -1.30327317, -0.90248431,  1.77890034, -0.0149508 ,  0.81900314],
       [-1.80153   , -0.30535488, -2.35543798, -0.75046152, -1.02191407,
         1.74697914, -3.00861008,  1.11659397,  2.28354613,  4.82541739,
         4.65206129, -3.3560023 , -4.16857872,  2.24899879,  0.05290312],
       [-2.80396182, -2.1224001 , -0.70256968,  0.01968298, -0.37351612,
        -1.45279046,  1.99712268, -2.31035042, -3.44661946, -2.67972786,
        -2.04433901,  1.52172565,  0.53841013, -1.96192378, -3.05568082],
       [-1.60059262,  1.64708566,  0.0093217 , -0.14668038, -0.80510888,
         2.8496906 ,  0.94764365, -2.43077987, -4.16765332,  0.0308911 ,
         2.27130812, -3.60655501,  0.807795  ,  1.80024723,  1.55475237],
       [-0.1692692 , -3.8810166 , -0.67722992, -0.24722126,  1.28669576,
         2.77744672,  0.52891609, -3.2952314 , 

In [129]:
data.sum(axis=(0,2)).shape

(10,)

In [130]:
data.sum()

-23.335280516208428

In [131]:
data.sum(axis=1)

array([[-0.9719816 ,  1.8072136 , -0.06016453, -0.46255874,  2.15709669,
         1.45031699,  2.01377119, -1.64778996,  3.25945215, -4.45334334,
         4.10070709, -1.16078307, -2.99544897,  3.21627649, -6.83867051],
       [-5.07888472,  3.07976248,  7.67269051,  4.94326706, -5.62140652,
        -0.73192845,  0.93853133, -3.7844493 ,  3.09795675,  3.77838275,
        -0.09056826, -0.12194696, -0.26370176, -4.06590064,  1.14295405],
       [-0.53814609,  2.44368059, -1.27575557, -7.15520903,  1.71572012,
        -3.24565657, -2.31254961, -1.46709238, -2.41876226,  2.9969759 ,
        -1.57676402, -0.47006074,  3.23618648,  2.78345014,  1.19548449],
       [-3.66555491,  0.11325338, -2.13629177, -0.00798948,  3.22708846,
         2.50676117, -2.07442772,  0.12585709, -3.93138397,  1.88375745,
        -5.07446991, -3.89714426,  5.1629242 , -0.94942634, -5.96719363],
       [ 1.46828377, -5.42622351, -1.61743121,  2.92563723, -3.90295795,
         1.60137278,  0.35070526, -1.20752245, 

In [132]:
print(data)

[[[ 1.70642756  1.0149397  -0.00960989  0.29710372  0.52627252
   -0.77114994 -1.24443544  2.13601747  0.35013312  0.38062867
    0.29908304 -0.22540463 -0.38623389  0.17375786 -1.29383451]
  [-1.06613524  1.70410939 -1.21319833 -1.28941797  0.62699967
    0.18661138 -0.87170493  0.71094595  0.52714294  1.36429112
    0.89140221  0.01616189 -1.54747865  0.83771145  0.2401886 ]
  [ 0.16659037 -0.12874055 -0.53560357  0.8874169   1.06634417
   -0.05638132  2.68382967  0.91615902  0.5187992  -1.06599466
   -0.3377632  -1.44895938  0.75058174  0.08159418 -1.92629901]
  [-1.6571661  -0.12074635 -1.58099914 -0.31495392 -0.65123521
    1.21991684  1.27013949 -1.79185772 -0.9558605  -0.32888987
    1.23807646 -0.74282065 -1.29758032  1.15383781  1.70757029]
  [-0.96142583 -2.30218498 -0.19088624 -0.01016066 -0.53977033
   -0.58094243  0.30279346 -1.82496369  0.73204863 -0.93413149
    1.39140243  1.37505127 -0.21921813 -0.62852894  0.13074156]
  [-0.24499066  0.01658358  1.58056216  0.00358012

In [133]:
data = np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [134]:
data.sum()

45

In [135]:
data.sum(axis=0)

array([12, 15, 18])

In [136]:
data.sum(axis=1)

array([ 6, 15, 24])

In [137]:
a = np.array([1,2,3,4,5])
b=np.array([5,4,3,2,1])
a<b

array([ True,  True, False, False, False])

In [139]:
def pulse(x, position, height, width):
    return height * (x >=position) * (x<=(position + width))
x = np.linspace(-5,5,11)
pulse(x, position = -2, height = 1, width = 5)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [140]:
x = np.linspace(-4,4,9)
np.where(x<0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [145]:
np.select([x<-1, x<2, x>=2], [x**2, x**3, x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [142]:
x

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [144]:
np.choose([0,0,0,1,1,1,2,2,2],[x**2,x**3,x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [146]:
np.nonzero(abs(x) >2)

(array([0, 1, 7, 8], dtype=int64),)

In [147]:
x[np.nonzero(abs(x)>2)]

array([-4., -3.,  3.,  4.])

In [148]:
a = np.unique([1,2,3,3])
b = np.unique([2,3,4,4,5,6,5])
np.in1d(a,b)

array([False,  True,  True])